name: Update version
on:
  schedule:
    - cron: 0 * * * *

jobs:
  update-version:
    name: update-version
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run gitwerk semver-auto
        run: |
          CURRENT_VERSION=`cat VALD_CLIENT_CLJ_VERSION`
          VERSION=`curl -s https://api.github.com/repos/vdaas/vald-client-java/releases/latest | jq '.tag_name'`
          if [ "" = "${VERSION}" ]; then
            echo "the version is empty"
            exit 0
          fi

          VERSION="v${VERSION}"

          if [ "$CURRENT_VERSION" = "${VERSION}" ];then
            echo "not updated"
            exit 0
          fi

          VERSION=`curl -sL "http://search.maven.org/solrsearch/select?q=vald-client-java&rows=20&wt=json&start=0" | jq -r '.response.docs[] | select(.a == "vald-client-java") | .latestVersion'`
          VERSION="v${VERSION}"

          if [ "$CURRENT_VERSION" = "${VERSION}" ];then
            echo "not uploaded to maven repository"
            exit 0
          fi

          echo "${VERSION}" > VALD_CLIENT_CLJ_VERSION

          curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod a+x lein
          ./lein pom
          rm lein

          git config --global user.name "VDaaS org"
          git config --global user.email "ci@vdaas.org"
          git remote set-url origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git checkout main
          git add VALD_CLIENT_CLJ_VERSION
          git add pom.xml
          git commit --signoff -m ":bookmark: Release ${VERSION}"

          git tag ${VERSION}
          git remote set-url origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git push origin main
          git push origin ${VERSION}
        env:
          GITHUB_USER: ${{ secrets.VALDCLI_USER }}
          GITHUB_TOKEN: ${{ secrets.VALDCLI_TOKEN }}
